data = """[{"attributes": [{"id": "pot_type",
  "name": "Tipo de olla",
  "condition": "Free Input",
  "value_type": "string",
  "value_examples": ["Vaporeras",
  "Cacerola",
  "Olla a presion"],
  "user_input_value": "",
  "value_max_lenght": 255},
  {"id": "units_per_pack",
  "name": "Unidades por pack",
  "condition": "Free Input",
  "value_type": "number",
  "value_examples": "",
  "user_input_value": "1",
  "value_max_lenght": 18},
  {"id": "value_added_tax",
  "name": "IVA",
  "condition": "Restricted Input",
  "value_type": "list",
  "value_examples": ["Exento",
  "0 %",
  "10.5 %",
  "21 %",
  "27 %"],
  "user_input_value": "21 %",
  "value_max_lenght": ""},
  {"id": "import_duty",
  "name": "Impuesto interno",
  "condition": "Restricted Input",
  "value_type": "list",
  "value_examples": ["0 %",
  "1 %",
  "2.5 %",
  "4 %",
  "5 %",
  "8 %",
  "9.5 %",
  "10 %",
  "14 %",
  "15 %",
  "18 %",
  "19 %",
  "20 %",
  "23 %",
  "25 %",
  "26 %",
  "70 %"],
  "user_input_value": "0 %",
  "value_max_lenght": ""}]},

  {"shipping": [
    
    {"id": "mode",
  "name": "Metodo de Envio",
  "condition": "Restricted Input",
  "value_type": "list",
  "value_examples": [["custom",
  "me1",
  "me2",
  "not_specified"]],
  "user_input_value": "me2",
  "value_max_lenght": ""},
  
  {"id": "local_pick_up",
  "name": "Buscar en Local",
  "condition": "Restricted Input",
  "value_type": "list",
  "value_examples": [["True",
  "False"]],
  "user_input_value": "True",
  "value_max_lenght": ""},

  {"id": "free_shipping",
  "name": "Envio Gratis",
  "condition": "Restricted Input",
  "value_type": "list",
  "value_examples": [["True",
  "False"]],
  "user_input_value": "False",
  "value_max_lenght": ""},

  {"id": "logistic_type",
  "name": "Tipo de Logistica",
  "condition": "Restricted Input",
  "value_type": "list",
  "value_examples": [["fulfillment",
  "cross_docking",
  "self_service",
  "drop_off",
  "custom"]],
  "user_input_value": "drop_off",
  "value_max_lenght": ""}]},


  {"sale_terms": []},
  {"listing": [{"id": "listing_type",
  "name": "Campana de Cuotas",
  "condition": "Restricted Input",
  "value_type": "list",
  "value_examples": [[{"id": "gold_pro",
  "name": "Premium",
  "sale_fee_amount": 69171.52,
  "sale_fee_details": {"fixed_fee": 0,
  "gross_amount": 69171.52,
  "percentage_fee": 26.9569465,
  "meli_percentage_fee": 14.6569465,
  "financing_add_on_fee": 12.3},
  "listing_fee_amount": 0,
  "listing_fee_details": {"fixed_fee": 0,
  "gross_amount": 0}},
  {"id": "gold_premium",
  "name": "Oro Premium",
  "sale_fee_amount": 0,
  "sale_fee_details": {"fixed_fee": 0,
  "gross_amount": 0,
  "percentage_fee": 0,
  "meli_percentage_fee": 0,
  "financing_add_on_fee": 0},
  "listing_fee_amount": 0,
  "listing_fee_details": {"fixed_fee": 0,
  "gross_amount": 0}},
  {"id": "gold_special",
  "name": "Clasica",
  "sale_fee_amount": 37609.72,
  "sale_fee_details": {"fixed_fee": 0,
  "gross_amount": 37609.72,
  "percentage_fee": 14.6569465,
  "meli_percentage_fee": 14.6569465,
  "financing_add_on_fee": 0},
  "listing_fee_amount": 0,
  "listing_fee_details": {"fixed_fee": 0,
  "gross_amount": 0}},
  {"id": "gold",
  "name": "Oro",
  "sale_fee_amount": 0,
  "sale_fee_details": {"fixed_fee": 0,
  "gross_amount": 0,
  "percentage_fee": 0,
  "meli_percentage_fee": 0,
  "financing_add_on_fee": 0},
  "listing_fee_amount": 0,
  "listing_fee_details": {"fixed_fee": 0,
  "gross_amount": 0}},
  {"id": "silver",
  "name": "Plata",
  "sale_fee_amount": 0,
  "sale_fee_details": {"fixed_fee": 0,
  "gross_amount": 0,
  "percentage_fee": 0,
  "meli_percentage_fee": 0,
  "financing_add_on_fee": 0},
  "listing_fee_amount": 0,
  "listing_fee_details": {"fixed_fee": 0,
  "gross_amount": 0}},
  {"id": "bronze",
  "name": "Bronce",
  "sale_fee_amount": 0,
  "sale_fee_details": {"fixed_fee": 0,
  "gross_amount": 0,
  "percentage_fee": 0,
  "meli_percentage_fee": 0,
  "financing_add_on_fee": 0},
  "listing_fee_amount": 0,
  "listing_fee_details": {"fixed_fee": 0,
  "gross_amount": 0}},
  {"id": "free",
  "name": "Gratuita",
  "sale_fee_amount": 0,
  "sale_fee_details": {"fixed_fee": 0,
  "gross_amount": 0,
  "percentage_fee": 0,
  "meli_percentage_fee": 0,
  "financing_add_on_fee": 0},
  "listing_fee_amount": 0,
  "listing_fee_details": {"fixed_fee": 0,
  "gross_amount": 0}}]],
  "user_input_value": "gold_special",
  "value_max_lenght": ""}]}]"""

import json

all_settings_groups = json.loads(data)
for settings_group in all_settings_groups:
    for section_name in settings_group:
        if section_name == "shipping":
            
            for variable in settings_group[section_name]:
                if variable.get('id') == 'free_shipping':
                    print(variable)
                    free_shipping_settings = variable.get('user_input_value')

print(free_shipping_settings)